spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
jwt:
  key: kevin12341234123412341234123412341234adsfgeeettwaeaafasfsadf
  ATExpiration: 420
  RTExpiration: 420